currency-converter-api:
  url: https://openexchangerates.org/api/
  auth:
    token: f2c408f86dfd4751aee7543973ab2770
  retry-delay: 3000
  max-attempts: 3
  max-period: 10
  commission-percentage: 0.01
  refresh-cron: "3 0 * * * *"
