server:
  port: 9080

logging:
  level:
    root: info

services:
  exchange:
    url: https://openexchangerates.org
    rates-endpoint: /api/latest.json
    app-id: ca800d6c1f28496a9461bd842d20b919
    fee: 1.01
