server:
  port: 9080

logging:
  root: info

services:
  openexchange:
    url: https://openexchangerates.org/
    appId: f3c37613244e47979f50c0451a24291d

  exchangerates:
    url: http://127.0.0.1:8080
#        url: 10.11.12.13
    appId: a9a4c62d6dbea49c6ea892287f57fc24

cron:
  currency-rate-fetcher: "0 */5 * * * *"

spring:
  data:
    redis:
      port: 6379
      host: 192.168.43.78
