server:
  port: 9080
spring:
  profiles:
    active: test
logging:
  level:
    root: info

site:
  openexchangerates:
    url: https://openexchangerates.org/api

services:
  openexchangerates:
    app_id: ca800d6c1f28496a9461bd842d20b919

currencyConverter:
  commission: 1.01

default:
  target:
    currency: USD

scheduler:
  fetch:
    currency-rates:
      cron: "0 0 0 * * *" # every day at 00:00

data:
  redis:
    port: 6379
    host: localhost

async:
  currency-rates-fetch:
    threads-count: 2
  put-in-map:
    threads-count: 20