spring:
  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 9080

logging:
  root: info

services:
  openexchange:
    url: https://openexchangerates.org/
    appId: f3c37613244e47979f50c0451a24291d

  exchangerates:
    url: https://api.exchangeratesapi.io/v1
    appId: a9a4c62d6dbea49c6ea892287f57fc24

cron:
  currency-rate-fetcher: "0 0 * * * *"