server:
  port: 9080

logging:
  level:
    root: info

openExchangeRates:
  url: "https://openexchangerates.org"
  appId: ${OPEN_EXCHANGE_RATES_APPID}

payment:
  baseCurrency: USD
  exchangeFee: 1.01

currency:
  fetch:
    url: https://v6.exchangerate-api.com/v6/
    appId: 5ffab83bf33aa9ef905e62b6
    commission: 1
    cron: "0 0 12 * * ?" # Cron-выражения, которое запускает метод каждый день в 12:00