spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: payment-processing-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      enable-idempotence: true
      max-in-flight-requests-per-connection: 5
    listener:
      ack-mode: manual
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

server:
  port: ${SERVER_PORT:9080}

logging:
  level:
    root: info

currency:
  exchange:
    url: https://openexchangerates.org
    appId: 7b5e207c5c8a4fb9aeefaf900491cf6d
    commission: 1