server:
  port: 9080

logging:
  level:
    root: info

services:
  openexchangerates:
    app_id: ca800d6c1f28496a9461bd842d20b919


  currencyRateFetcher:
    cron: "0 0 0 * * *"

currencyConverter:
  commission: 1.01