server:
  port: 9080

logging:
  level:
    root: info

currency:
  rate:
    update:
      cron: "0 0 0 * * *" # Каждый день в полночь

exchangerates:
  api:
    url: "http://api.exchangeratesapi.io/v1/latest"
    access_key: " API_KEY" #ваш API_KEY
    base: "EUR" #базовая валюта
    symbols: "GBP,JPY,USD,RUB"
    #http://api.exchangeratesapi.io/v1/latest? access_key = API_KEY & base = USD & symbols = GBP,JPY,EUR
