server:
  port: 9080

logging:
  level:
    root: info

services:
  openexchange:
    url: https://openexchangerates.org/
    appId: f3c37613244e47979f50c0451a24291d

cron:
  currency-rate-fetcher: "0 0 * * * *"