spring:
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9080

logging:
  level:
    root: info

retry:
  retry: 5
  delay: 3000

currency-api:
  url: https://api.exchangeratesapi.io/v1/
  api-key: YOUR_API_KEY_SET_IN_DOT_ENV_FILE
  base-currency: EUR
  redis-key: currencyRates
  cron: "00 30 09 * * *"
  timeout:
    connection: 5000
    read: 1000
