server:
  port: 9080

logging:
  level:
    root: debug

currency:
  base_url: https://v6.exchangerate-api.com/v6/
  key_api: keyapi
  base_currency: USD
  cron: "0 0 8 * * *"

payment:
  exchange_appId: ca800d6c1f28496a9461bd842d20b919
  exchange_fee: 1.01