spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        pending_operation_channel:
          name: pending-operation-channel

  async:
    corePoolSize: 8
    maxPoolSize: 10
    queueCapacity: 1000
    threadNamePrefix: "task-executor-thread-"

server:
  port: 9080

logging:
  level:
    root: info

currency:
  rate:
    fetch:
      cron: 0 3 * * * *
