spring:
  profiles:
    active: dev

server:
  port: 9080

currency:
  cron: "0 0 0 * * *"
  exchange:
    url: "http://api.exchangeratesapi.io/v1/"
    apiKey: "856ac664093bbf92b68d11ac46543ab6"
    baseCurrency: "" #функция не доступна для бесплатных аккаунтов
    actualCurrency: "EUR,USD,RUB,BYN"
    convert:
      roundingMode: "HALF_UP"
      scale: "2"

