server:
  port: 9080

logging:
  level:
    root: info

openExchangeRates:
  url: "https://openexchangerates.org"
  appId: ${OPEN_EXCHANGE_RATES_APPID}

payment:
  baseCurrency: USD
  exchangeFee: 1.01