name: CI Pipeline

on:
  pull_request:
    branches:
      - phoenix-master-stream8

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Run Gradle Test
        run: ./gradlew test --stacktrace
